---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Ensure postfix_exporter is running and enabled at boot.
      service:
        name: postfix_exporter
        state: started
        enabled: true

    - name: Verify postfix_exporter is responding to requests.
      uri:
        url: http://localhost:9154
        return_content: true
      register: metrics_output
      failed_when: "'Metrics' not in metrics_output.content"
